### ISSUE TITLE
[Bug]: Headings like Legal, Info, Explore, etc are not visible

### ISSUE THREAD

**Issue by Aditi22Bansal** [GameSphere-MultiPlayer/Community-Page#101]
### Give a brief about the bug ✍️

Description
Headings like Legal, Info, Explore, etc are not visible. They are written in black and the background is also black so the text is not visible.
![Screenshot 2024-05-15 151759](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/142652964/4b587ef8-90ac-4b56-aa64-0251e697b363)

### What is the expected behavior? 🤔

Description
Expected is that the text is visible. 

### Provide step by step information reproduce the bug 📄

Description
I can change the font and colour of the text to make it visible.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by nilesh5566** [comment]
Please assign me this issue under GSSoc'24.
