### ISSUE TITLE
 add hover effect to navbar

### ISSUE THREAD

**Issue by Hemav009** [GameSphere-MultiPlayer/Community-Page#11]
![Screenshot 2024-05-10 194804](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/109607812/7ea460c4-2bc6-44f1-8dfe-f37add36790c)

Hover effects are visual changes that occur when a user hovers their mouse cursor over an element, such as a link or button, on a webpage. (color change)

### Point down the features

color change

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Hemav009 Could you please explain more, if possible

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly as on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Hemav009** [comment]
> @Hemav009 Could you please explain more, if possible

![Screenshot 2024-05-10 200415](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/109607812/e418136c-d536-488c-b1c7-f1d3c34e917d)

Refer the above image.

I want to create an effect where, upon hovering the cursor over the 'About' link, the color changes and an underline appears.

**Comment by SougataXdev** [comment]
@Hemav009 please assign this task to me

**Comment by SougataXdev** [comment]
@Durgesh4993 please assign this task to me

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@Durgesh4993

**Comment by SalehaTabassum** [comment]
@Durgesh4993 please assign this issue to me

**Comment by gupta-ritik** [comment]
@Durgesh4993 please assign this task to me.

**Comment by Nehakumari1208** [comment]
PLease assign this task to me...i will fix it

**Comment by vignesh-0512** [comment]
As a gssoc'24 contributor and also i have good experience in adding some transition and hover effect in navbar in order to add good and neat hover effect to navbar i would like to assign this issue to me.

**Comment by Aleena-Memon** [comment]
@Durgesh4993 please assign me this task so that i can work on it under GSSOC24

**Comment by Kashishoza** [comment]
please assign it to me under gssoc 2024

**Comment by reshamsai150** [comment]
adding hover effect to the navbar could make it more attractive assign this issue to me @Durgesh4993
