### ISSUE TITLE
Live translation 

### ISSUE THREAD

**Issue by mahek0620** [GameSphere-MultiPlayer/Community-Page#111]
### Point down the features

Real-time language translation for in-game chat and communication, enabling players from different language backgrounds to communicate and collaborate effectively during multiplayer sessions.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@mahek0620 Could you please explain more what you want to do, if possible you can also add screenshot.

**Comment by Durgesh4993** [comment]
@mahek0620 Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by mahek0620** [comment]
The game's chat system recognizes incoming messages from players.
The text is then translated from the sender's language into the receiver's language in real-time.
The translated message is displayed in the recipient's chat interface, allowing them to understand the message even if it's in a different language.
Benefits:  By supporting multiple languages, the game becomes accessible to players from diverse linguistic backgrounds, expanding the player base and fostering a more inclusive gaming community. Effective communication is crucial for teamwork and collaboration in multiplayer games.
