### ISSUE TITLE
[New Feature]: Adding scroll to top feature button

### ISSUE THREAD

**Issue by reshamsai150** [GameSphere-MultiPlayer/Community-Page#114]
### 🎮 feature Request

The scroll-to-top button appears when the user starts scrolling down the page.
When clicked, it smoothly scrolls the page back to the top

### Point down the features

Clicking the button will smoothly scroll the page to the top 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by reshamsai150** [comment]
Assign this issue to me @Durgesh4993

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Varshajha5** [comment]
I want to work on this issue @Durgesh4993 .plesase assign this issue to me
