### ISSUE TITLE
[Bug]: Responsive Search bar 

### ISSUE THREAD

**Issue by VSNSRUJANA123** [GameSphere-MultiPlayer/Community-Page#116]
### Give a brief about the bug ✍️

Description:
In this project below 766px width the search bar doesn't display properly when click on search icon

https://github.com/GameSphere-MultiPlayer/Community-Page/assets/127814497/fd78bbe1-1dac-45b9-b2ee-eb43c4883e93

@Durgesh4993 please assign this issue to me 

### What is the expected behavior? 🤔

Description: Create a Responsive search bar suitable in all devices 

### Provide step by step information reproduce the bug 📄

steps : Create a responsive search bar when click  on search icon

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayushrskiaa** [comment]
please assign it to me. I can fix it.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Durgesh4993** [comment]
@ayushrskiaa Please raise any other issue, i'll assign you

**Comment by Suruchibharti** [comment]
hii ,
I'm GSSoC'24 contributor , I have experienced in HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the issue.
