### ISSUE TITLE
[Bug]: About us page not connected

### ISSUE THREAD

**Issue by agastya3636** [GameSphere-MultiPlayer/Community-Page#117]
### Give a brief about the bug ✍️

 About us page not connected when clicked it does nor redirect.

### What is the expected behavior? 🤔

![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/124435030/2ad3014c-344e-4c0e-96bb-d1f68aa87385)
it should redirect to about us page

### Provide step by step information reproduce the bug 📄

i will fix the html

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by agastya3636** [comment]
@Durgesh4993  could you please assign it to  me

**Comment by Manaregr8** [comment]
> @Durgesh4993 could you please assign it to me

This issue is already being handle in an issue.
#87 
Thanks for your efforts, find new issues and will assign them too you.
for any doubt feel free to connect at https://discord.com/channels/1112374263039660063/1232836145902129163
