### ISSUE TITLE
[Bug]: About us page navbar does not have light veiw mode.

### ISSUE THREAD

**Issue by agastya3636** [GameSphere-MultiPlayer/Community-Page#119]
### Give a brief about the bug ✍️

![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/124435030/367a3c85-03ac-4e30-81f6-ffc45611ed8a)
in above image navbar does not contain light view mode while home page has.
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/124435030/99fb0327-b8a0-470f-941a-c59b345b4b93)
 

### What is the expected behavior? 🤔

All the pages should have same navbar

### Provide step by step information reproduce the bug 📄

I will create the navbar same as the home page.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Raksha-Vats** [comment]
Please assign this issue to me under GSSOC

**Comment by Manaregr8** [comment]
> Please assign this issue to me under GSSOC

@Raksha-Vats Please raise an issue than will assign it to you.

**Comment by agastya3636** [comment]
@Durgesh4993 could you please assign it to me
