### ISSUE TITLE
[Bug]: Play games button is not working

### ISSUE THREAD

**Issue by pallasivasai** [GameSphere-MultiPlayer/Community-Page#121]
### Give a brief about the bug ✍️

I want to add an our gamesphere homepage at here so that user can able to play games from it!

![Chrome Gaming _ Home - Google Chrome 17-05-2024 11_30_02](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/56314427/0630e4ec-39c1-43de-9c0e-74117a397f7e)

### What is the expected behavior? 🤔

expected behavior will be like this
![GameSphere  - Google Chrome 17-05-2024 11_31_56](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/56314427/fe6e6692-8c4b-48d4-a8d6-04d8b672699d)

### Provide step by step information reproduce the bug 📄

just I will add this webpage link in the hyper link only

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@pallasivasai Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
