### ISSUE TITLE
Update the UI of Search result

### ISSUE THREAD

**Issue by Anshu3301** [GameSphere-MultiPlayer/Community-Page#125]
### 🎮 feature Request

The search results are in an unordered way. The UI does not look good.

### Point down the features

I would like to align it in a better way to upgrade the UI.

### Current :
![Screenshot (175)](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/134282893/5732e5af-bf76-4ee1-b7d3-9513347f046d)

### Updated : 
![Screenshot (176)](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/134282893/e8e34a9d-e03c-444c-bf7e-50f054f5e750)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Anshu3301** [comment]
Ok Sir!

**Comment by Anshu3301** [comment]
Ok Sir!
