### ISSUE TITLE
adding favicon

### ISSUE THREAD

**Issue by anuza08** [GameSphere-MultiPlayer/Community-Page#13]
### 🎮 feature Request

feature logic and basic description

### Point down the features

feature points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@anuza08 could you please explain more

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly as on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by ayushrskiaa** [comment]
hello @Durgesh4993 sir, I can add favicon to it. please assign this to me under GSSOC'24.
thank you.

**Comment by Pratyaksh0910** [comment]
Hey there! I'm Pratyaksh Agrawal, a full-stack MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC.
You can find me on LinkedIn : https://www.linkedin.com/in/pratyaksh-agrawal-2aa032220/
Looking forward to contributing to GSSOC 2024!

**Comment by Nehakumari1208** [comment]
PLease assign this task to me...i will fix it

**Comment by Durgesh4993** [comment]
@Pratyaksh0910 @Nehakumari1208 Please raise any other issue, then i'll assign you 

If you have any doubt you can directly as on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by ayushrskiaa** [comment]
> @anuza08 @ayushrskiaa  could you please explain more

![images (4).jpeg](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/130389607/f83a9a93-518c-470c-ba03-29bead2d02c2)

I am talking about adding this type of logo to the website

**Comment by Pratyaksh0910** [comment]
Hey there! I'm Pratyaksh Agrawal, a full-stack MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC.
You can find me on LinkedIn : https://www.linkedin.com/in/pratyaksh-agrawal-2aa032220/
Looking forward to contributing to GSSOC 2024!

@Durgesh4993

**Comment by Durgesh4993** [comment]
@ayushrskiaa i want to know about design

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by ayushrskiaa** [comment]
Thank you
