### ISSUE TITLE
[Bug]: Search bar should be closed.

### ISSUE THREAD

**Issue by abhiperfect** [GameSphere-MultiPlayer/Community-Page#130]
### Give a brief about the bug ✍️

Bug: The search bar remains open even after clicking outside of it. It should automatically close when users click anywhere outside of the search bar to ensure a smoother and more intuitive user experience.

### What is the expected behavior? 🤔

The expected behavior is that when the user clicks outside of the search bar, the search bar should close automatically. This ensures that the search functionality does not interfere with other interactions on the page and provides a more user-friendly experience.

### Provide step by step information reproduce the bug 📄

1. Open the website/application with the search bar feature.
2. Click on the search bar to activate it.
3. Without entering any search query, click anywhere outside the search bar.
4. Notice that the search bar remains open instead of closing as expected.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
