### ISSUE TITLE
[New Feature]: Adding a favicon to the website.

### ISSUE THREAD

**Issue by abhiperfect** [GameSphere-MultiPlayer/Community-Page#131]
### 🎮 feature Request

Adding a favicon to the website would enhance its branding and improve user experience by displaying a custom icon in the browser tab.

### Point down the features

Adding a favicon enhances branding, professionalism, and user experience by providing a recognizable icon in the browser tab, improving navigation, visual appeal, and accessibility.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
> ### 🎮 feature Request
> Adding a favicon to the website would enhance its branding and improve user experience by displaying a custom icon in the browser tab.
> 
> ### Point down the features
> Adding a favicon enhances branding, professionalism, and user experience by providing a recognizable icon in the browser tab, improving navigation, visual appeal, and accessibility.
> 
> ### Select program in which you are contributing
> GSSoC24
> 
> ### Code of Conduct
> * [x]  I follow CONTRIBUTING GUIDELINE of this project.

Issue already Addressed

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
