### ISSUE TITLE
[New Feature]: Update twitter logo.

### ISSUE THREAD

**Issue by abhiperfect** [GameSphere-MultiPlayer/Community-Page#132]
### 🎮 feature Request

The feature involves updating the Twitter logo on the website to maintain brand consistency, enhance aesthetics, improve user recognition, and ensure a positive user experience.

### Point down the features

Updating the Twitter logo on the website maintains brand consistency, enhances aesthetics, improves user recognition, and ensures a positive browsing experience, aligning with latest branding guidelines and fostering brand recognition.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
