### ISSUE TITLE
[New Feature]: Making About Us and Contribute Page 

### ISSUE THREAD

**Issue by seeratfatima19** [GameSphere-MultiPlayer/Community-Page#134]
### 🎮 feature Request

I am proposing to add About Us page which will basically be guiding people about the project and website.
Also, I can work on the Contribute page which will show the users how they can further contribute to the gaming sphere. The style will be minimal and clean, having good readability.

### Point down the features

- About Us page
- Contribute page having steps to guide how to contribute to gaming sphere

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@seeratfatima19 Please raise any other issue, because someone is already working on it....
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
