### ISSUE TITLE
[Bug]: Fauget.gif 

### ISSUE THREAD

**Issue by aursh24** [GameSphere-MultiPlayer/Community-Page#139]
### Give a brief about the bug ✍️

Description,
The `Fauget.gif` is not looking appealing in the white mode. It doesn't give a sense of spacing between the Navigation Menu and the next attached image.

### What is the expected behavior? 🤔

Description,
It should have spacing from the top and bottom so that it looks appealing in white mode and gives a minimalist and appealing look.

### Provide step by step information reproduce the bug 📄

1. Open the application in white mode.
2. Navigate to the part of the page containing `Fauget.gif`. Gif represents the Chrome Gaming logo.
3. Observe the lack of spacing between the Navigation Menu and the image and forthcoming image.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by aursh24** [comment]
please assign me to resolve this issue under GSSOC'24.

**Comment by Varshajha5** [comment]
Durgesh4993 assign this issue to me  under GSSOC 24
