### ISSUE TITLE
color of footer headings in about page should be fixed

### ISSUE THREAD

**Issue by Ridhima10** [GameSphere-MultiPlayer/Community-Page#148]
### Give a brief about the bug ✍️

The color of heading  in about page is very light and is different from other pages
![Screenshot 2024-05-19 181238](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/85826117/a53e8b19-0d7e-4807-a220-51e55bc0317d)

### What is the expected behavior? 🤔

It should be same as the footer in other pages

### Provide step by step information reproduce the bug 📄

I will fix it and color it to white

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
Hi @Ridhima10,

I think your branch is not updated, please sync your branch as its visible (Displayed in Below Pic).

Thank You.
![saasdasxsaxas](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/99804338/dfe28d37-da2e-4223-bb25-f1a3944246d9)
