### ISSUE TITLE
[New Feature]:  Would u like to add preloader?

### ISSUE THREAD

**Issue by Anjaliavv51** [GameSphere-MultiPlayer/Community-Page#149]
### 🎮 feature Request

feature logic and basic description
A preloader is an essential interface element that appears on a web page while its content is being loaded. It serves as a visual cue to users, letting them know that the website is actively processing data and hasn’t crashed.

### Point down the features

feature points
1.User Experience Enhancement
2.Visual Feedback
3.Customization
4.Responsive Interaction

Feature:

https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/154777864/7ef2cd29-dc32-44db-9225-81f4d28bdc45

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
Hi @Anjaliavv51,

Pre loader is nice just can we have the chrome gaming gif in it, It will look cool.

Thank You
![kasjknxkajnsxka](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/99804338/2a321c69-fe98-49ef-9513-1bfe5a3cb4b2)

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Anjaliavv51** [comment]
issue is done please check PR #169 


### Added Code!
```
<!-- Preloader Style-->
    <style>
      .preloader{
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: black;
  transition: opacity 5s, visibility 5s;
  z-index: 1000;
}

.preloader--hidden{
  opacity: 0;
  visibility: hidden;
}
.preloader img{
  height: 200px;
  width: 200px;
  border-radius: 1000px;
}
    </style>
<div class="preloader">
      <img class="center" src="Fauget.gif" alt="" />
    </div>
    <script>
      window.addEventListener("load", () => {
const loader = document.querySelector(".preloader");
loader.classList.add("preloader--hidden");
loader.addEventListener("transitionend", () => {
document.body.removeChild(loader);
});
});
    </script>
```
