### ISSUE TITLE
[Bug]: Upload button is not working

### ISSUE THREAD

**Issue by anuza08** [GameSphere-MultiPlayer/Community-Page#15]
### Give a brief about the bug ✍️

Description
The upload btn is not working 

### What is the expected behavior? 🤔

Description

### Provide step by step information reproduce the bug 📄

Description

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
We don't have database where we store the games, so i am closing this issue now

**Comment by Durgesh4993** [comment]
If you have any doubt  or intrested to work on that you can directly  text me on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
