### ISSUE TITLE
[Bug]: 1.No options are visible in dropdown icon in responsive mode when changed to dark.  2. Also the dropdown icon is not visible in light mode in responsive mode.

### ISSUE THREAD

**Issue by curecode11** [GameSphere-MultiPlayer/Community-Page#150]
### Give a brief about the bug ✍️

The drop down menu items and drop down icon is not visible in responsive dimensions in dark and light modes respectively.

### What is the expected behavior? 🤔

Drop down items and icon should be visible to the users.

### Provide step by step information reproduce the bug 📄

Open inspect in chrome and open responsive mode.
Now open the drop down everything is black.
Change to light mode now the icon itself become invisible.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by curecode11** [comment]
@Durgesh4993 and @Manaregr8 sir , please assign the task to me I will resolve the bug and will be happy to work upon it.

**Comment by Manaregr8** [comment]
> @Durgesh4993 and @Manaregr8 sir , please assign the task to me I will resolve the bug and will be happy to work upon it.

Please provide a respective video or screenshot that aligns with the bug you are referring too. 

Thank You

**Comment by curecode11** [comment]
here it is 
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/118065498/73b3424a-506d-43ac-a02d-99e794031a54)
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/118065498/cda8d76e-80f4-4069-9325-33441bc083c8)

**Comment by Varshajha5** [comment]
please assign this issue to me @Durgesh4993 and @Manaregr8 sir
