### ISSUE TITLE
#share button position overlaping with nav bar and search bar close button missing

### ISSUE THREAD

**Issue by roushanverma23** [GameSphere-MultiPlayer/Community-Page#152]
### Describe the bug ✍️

![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/137530796/1ce89b93-6b7a-49b9-bfbd-849cb306232e)

![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/137530796/2f7685fc-608b-400c-9c26-7618bbbfdc53)

![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/137530796/fec94758-4496-4d2e-9ffb-2658c631f1ae)

### Provide step by step information reproduce the bug 📄

adding the search bar close button and positioning the share button below nav bar

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by roushanverma23** [comment]
@Manaregr8 please assign it to me


![gssoc](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/137530796/bb96de20-aea4-4d83-91c3-e6de1fcd407d)

**Comment by roushanverma23** [comment]
@Manaregr8 please review it. And if all is good please merge my PR.
Thank You 😃

**Comment by Manaregr8** [comment]
> @Manaregr8 please review it. And if all is good please merge my PR. Thank You 😃

Please use latest fork the share button has already been positioned to all responsive views.

U can raise issues over navbar responsiveness and other pages as well.
Thank You.
