### ISSUE TITLE
[New Feature]:  Timeline in About us Page

### ISSUE THREAD

**Issue by Bhavishya2601** [GameSphere-MultiPlayer/Community-Page#154]
### 🎮 feature Request

I was hoping to add a timeline in the About us page which would contain the history of the website, It would look great and it also makes the webpage more professional and attractive

### Point down the features

Something like this
![Screenshot 2024-05-20 153225](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/147748752/e27f31c7-7cf4-423e-9c67-b247073818a3)

(This is from my previous project)

Hope you would assign this task to me

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
Hi @Bhavishya2601,

Please go for it, Just look for overall template flow and UI/UX.

Thank You

**Comment by tanvikoranne** [comment]
I would like to work upon this issue. Please assign me this.
