### ISSUE TITLE
[Bug]:  The Gif on the Homepage needs to be changed

### ISSUE THREAD

**Issue by Bhavishya2601** [GameSphere-MultiPlayer/Community-Page#155]
### Give a brief about the bug ✍️

The gif on the homepage is in black so when we change the theme from black to white, it is really obvious that it is a gif, so we need to change it, as it makes the website look unprofessional

![Screenshot 2024-05-20 153400](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/147748752/77ad1dc2-4461-4072-8812-aa7428c40a82)

### What is the expected behavior? 🤔

We need to change the gif, so that the webpage looks professional, 

### Provide step by step information reproduce the bug 📄

I have already done the needful, I just want you to assign this issue to me so that I can create a PR

Believe me It's gonna look amazing

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
> ### Give a brief about the bug ✍️
> The gif on the homepage is in black so when we change the theme from black to white, it is really obvious that it is a gif, so we need to change it, as it makes the website look unprofessional
> 
> ![Screenshot 2024-05-20 153400](https://private-user-images.githubusercontent.com/147748752/332026295-77ad1dc2-4461-4072-8812-aa7428c40a82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDgzNjQsIm5iZiI6MTcxNjMwODA2NCwicGF0aCI6Ii8xNDc3NDg3NTIvMzMyMDI2Mjk1LTc3YWQxZGMyLTQ0NjEtNDA3Mi04ODEyLWFhNzQyOGM0MGE4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxNjE0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDVkOWMzN2QyNWZjZWRlNTY0ZjBjMjI4YTMxZjc3M2YwNjUwNmI1ODY1ZTUwNGRmNDdjZDFmZmM1NDM0NTIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LN9ez9blA9td7-XVmgWoXsWxU4-DpAvZg1TrPW8PNEk)
> 
> ### What is the expected behavior? 🤔
> We need to change the gif, so that the webpage looks professional,
> 
> ### Provide step by step information reproduce the bug 📄
> I have already done the needful, I just want you to assign this issue to me so that I can create a PR
> 
> Believe me It's gonna look amazing
> 
> ### Select program in which you are contributing
> GSSoC24
> 
> ### Code of Conduct
> * [x]  I follow CONTRIBUTING GUIDELINE of this project.

Hi @Bhavishya2601 

If it turns out as expected, it will indeed be a remarkable achievement. I eagerly anticipate your Pull request.

Thank you.

**Comment by Manaregr8** [comment]
> Hi, could you please assign it to me?

Hi @medhakashyap,

Could you please raise new issues in the current repository? There seem to be quite a few of them. Since this program operates on a first-come, first-served basis, please keep an eye out for new issues, and I'll make sure to assign them to you.

Thank you for your efforts. Keep exploring!

**Comment by Bhavishya2601** [comment]
@Manaregr8  Can you please tell me which font, you like more
1) 
![Screenshot 2024-05-21 233358](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/147748752/1e251af7-d219-47c6-9376-c4cb885bfa8e)

2)
![Screenshot 2024-05-21 233436](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/147748752/7b28344e-37fa-44b5-9c35-20ce7b109e54)

I'll use that one
