### ISSUE TITLE
Responsive nav bar & nav bar invisible in light mode 

### ISSUE THREAD

**Issue by roushanverma23** [GameSphere-MultiPlayer/Community-Page#159]
### 🎮 feature Request

Responsive nav bar and alignment or social handles
nav bar is invisible in light mode for smaller screen size

### Point down the features

![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/137530796/cd2cad4f-5567-432e-8d44-9afcdee6ee96)

<br/>

![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/137530796/e8ef6898-6373-48f1-b3db-c12ffd1d7727)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
> @Manaregr8 Please assign this task.
Hi @roushanverma23 

The issue you mentioned is being resolved in another issue,
Keep on hunting issues and collaborating.

Thank You.
