### ISSUE TITLE
[Bug]:  search bar not clearly visible when in light mode

### ISSUE THREAD

**Issue by Saimanjari777** [GameSphere-MultiPlayer/Community-Page#161]
### Give a brief about the bug ✍️

Description

The color of the search bar is black in color. It is not clearly visible when it is in light mode.
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/130165687/0249786e-6aab-48e2-9939-9a7d9dc38324)

### What is the expected behavior? 🤔

Description
It should be visible and clear.

### Provide step by step information reproduce the bug 📄

Description
I will change the color of the search bar which is visible when in light mode
Please assign this task to me @Ga

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
Please raise any other issue, because someone is already working on it
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
