### ISSUE TITLE
[Bug]: Play Games page and Contribute page becomes non-clickable after accessing the Products page.

### ISSUE THREAD

**Issue by Qanta-31** [GameSphere-MultiPlayer/Community-Page#164]
### Give a brief about the bug ✍️

Description
When we go to Products page and then click on Play Games or Contribute page they are not opening.

### What is the expected behavior? 🤔

Description
Play Games and Contribute page must open when we click on them.

### Provide step by step information reproduce the bug 📄

Description
Using HTML and JavaScript. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Qanta-31** [comment]
@Durgesh4993 could you please assign this task to me, I would be happy to work on it.

**Comment by Durgesh4993** [comment]
@Qanta-31 Please clone latest code, there are some change are occured in website

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
