### ISSUE TITLE
[New Feature]: Navbar should be visible while scrolling

### ISSUE THREAD

**Issue by r7projects-shayan** [GameSphere-MultiPlayer/Community-Page#174]
### 🎮 feature Request

feature logic and basic description

The navbar is currently not visible while scrolling down the page in all the pages. It should be visible even while scrolling.

![Screenshot 2024-05-23 000248](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/167475552/47939caf-0bab-48c0-ab3d-0b6579a5dfcb)
![Screenshot 2024-05-23 000254](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/167475552/9c4afc51-79f1-47db-9c96-1543c49fbd24)

### Point down the features

feature points

Fixing the navbar on top, so that it's visible while scrolling

Adding a backdrop blue effect 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by shrutisharma32** [comment]
I want to work on this issue. Please assign me this.

**Comment by r7projects-shayan** [comment]
@Durgesh4993 I have already fixed the issue. Kindly assign it to me so that I can raise the pull request
