### ISSUE TITLE
Proper Arrangement of files + Responsive Web Page

### ISSUE THREAD

**Issue by Aditya01229** [GameSphere-MultiPlayer/Community-Page#18]
### 🎮 feature Request

Currently the files of the Web Page are not properly arranged and managed, I'll arrange it properly for better understanding and easy management of files. Also the Web Page is not Responsive enough which is making it look ugly. So will also make it responsive for better UX.

### Point down the features

The Web Page will be responsive.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE]() of this project.
- [ ] Proper Folder Structure.
- [ ] Fixed Responsiveness for better UX.

**Comment by Aditya01229** [comment]
Please assign it to me! I'll solve this issues.

**Comment by Durgesh4993** [comment]
Could you please explain more what you want to do, I have already assigned some tasks. if possible you can also add screenshot.

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Rajneeshkarya** [comment]
Hi @Aditya01229 , I would like to work on this issue, Could you assign it to me under GSSOC'24?

**Comment by Aditya01229** [comment]
https://github.com/GameSphere-MultiPlayer/Community-Page/assets/114353434/b6d86e4e-09de-4005-af3c-7618777ef63b

![Screenshot 2024-05-12 154132](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/114353434/86cb1098-89a1-4156-9ea6-7e49e6a0eabe)

@Durgesh4993 As in the video we can see the Website is not visually appealing at different size. So I will make it responsive to adapt all sizes. 
Also the folder structure, name of files is not that systematic. So I'll just do the basic task of giving proper name, making css, scripts, images folder and transferring files to their respective place and also make the necessary changes in index.html i.e. correct all the paths accordingly.
