### ISSUE TITLE
[Bug]: Navbar is twice on product page

### ISSUE THREAD

**Issue by Bhavishya2601** [GameSphere-MultiPlayer/Community-Page#180]
### Give a brief about the bug ✍️

on the product page, the navbar is there two times, I want to change it to one

### What is the expected behavior? 🤔

Deleting one of them

### Provide step by step information reproduce the bug 📄

![Screenshot 2024-05-23 223805](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/147748752/c7730d0f-38b1-42ff-8305-3d3b077b5958)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Bhavishya2601 Add our games on product page

**Comment by Bhavishya2601** [comment]
@Durgesh4993  add a level as well
