### ISSUE TITLE
[Bug]: Problem regarding the "JOIN NOW" text on the button of discord server section

### ISSUE THREAD

**Issue by shreya-paul-17** [GameSphere-MultiPlayer/Community-Page#182]
### Give a brief about the bug ✍️

Description:
The "JOIN NOW" text on the button in the discord server community in this project is not getting visible. Initially if the page is in dark mode then there won't be any problem neither the problem will be seen if we are reloading the page. But when we are switching the page from light mode to dark mode then the text is getting invisible in the button. The text is not becoming visible unless the button is being hovered over it.

Here is a screenshot of the current issue:

![community-page](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/135226069/1dbe49f9-f5d0-4ea3-b569-3934482cb941)

Could you please assign this task to me? I would like work on this issue. I am hopeful to bring the expected results effectively.

### What is the expected behavior? 🤔

The text should be visible irrespective of the fact being hovered. Also, even if it is switched from light mode to dark mode the tesxt on the button should get visible. 

Also the button is bit outside of the abstract shape of the discord server. It needs to get a bit inside the shape. So I think a bit of styling is also required so that the button gets exactly into the shape.

### Provide step by step information reproduce the bug 📄

Description:
1. Text should be made visible on the button.
2. A slight styling of the button is also required. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)

**Comment by shreya-paul-17** [comment]
But the same issue still persists and is even being raised by somebody else few minutes back.
