### ISSUE TITLE
 Alignment of upload button

### ISSUE THREAD

**Issue by Hemav009** [GameSphere-MultiPlayer/Community-Page#183]
### Give a brief about the bug ✍️

The upload button is not aligned correctly.

### What is the expected behavior? 🤔

button should be below the image

### Provide step by step information reproduce the bug 📄

by changing some css properties.
I made it look like this 

![Screenshot 2024-05-24 013553](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/109607812/adea6d57-7950-4f2c-8637-33bdc78ade09)

from this

![Screenshot 2024-05-24 013559](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/109607812/dd05341b-7990-4c17-b4ed-ac9cd69b8ca4)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Deepthi-Ramineni** [comment]
I would like to work on it. Can you please assign this to me?

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
