### ISSUE TITLE
[New Feature]: Adding persistence to theme in the web-page using local storage

### ISSUE THREAD

**Issue by kauxp** [GameSphere-MultiPlayer/Community-Page#184]
### 🎮 feature Request

When the page is reloaded, the theme resets to default, which is dark. When a user changes the theme, it should persist through reloads. For example, when I change the page to light, and reload the page, or close the site and visit some other time, the theme should remain light.

### Point down the features

- Persist the website theme through reloads

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by kauxp** [comment]
please assign this issue to me

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)

**Comment by kauxp** [comment]
I will work on this and report to you!

**Comment by kauxp** [comment]
Please add the level for this issue.
