### ISSUE TITLE
[Bug]: Dot-Box game is not at all responsive for mobile  devices

### ISSUE THREAD

**Issue by mondalsurojit** [GameSphere-MultiPlayer/Community-Page#185]
### Give a brief about the bug ✍️

Description
The Dot-Box game is not at all responsive for mobile devices.

![Screenshot (296)](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/114282267/a57acb79-3472-4f59-98a2-93804ff5654f)

### What is the expected behavior? 🤔

Description
The Dot-Box game must have been responsive, and adaptive to all type of mobile screen sizes 

### Provide step by step information reproduce the bug 📄

Description

Open the site: [https://gamesphere-multiplayer.github.io/Dot-Box/](https://gamesphere-multiplayer.github.io/Dot-Box/) in a mobile device

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### Urgency (Optional)

High priority

**Comment by Durgesh4993** [comment]
@mondalsurojit create issue on dot-box project

**Comment by mondalsurojit** [comment]
@Durgesh4993 Ok sir
