### ISSUE TITLE
[New Feature]: Need to create a Nodejs based backend for better functionality

### ISSUE THREAD

**Issue by sambitsingha** [GameSphere-MultiPlayer/Community-Page#187]
### 🎮 feature Request

For a modern level website , there is always a need for a backend based on Node / Django / Php / Ruby. As this wwebsite doesn't currently have a backend , I would like to create the needful. 

### Point down the features

- The backend will be created on Nodejs and Expressjs ( JS based )
- To keep the frontend like HTML , a similar templating language **EJS** will be used , which is just like HTML
- After creating the basic backend of the website , it will be deployed on Vercel

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by sambitsingha** [comment]
@Manaregr8 Please see to it

**Comment by sambitsingha** [comment]
@Durgesh4993

**Comment by Manaregr8** [comment]
@Durgesh4993 Please look into this one. 

> ### 🎮 feature Request
> For a modern level website , there is always a need for a backend based on Node / Django / Php / Ruby. As this wwebsite doesn't currently have a backend , I would like to create the needful.
> 
> ### Point down the features
> * The backend will be created on Nodejs and Expressjs ( JS based )
> * To keep the frontend like HTML , a similar templating language **EJS** will be used , which is just like HTML
> * After creating the basic backend of the website , it will be deployed on Vercel
> 
> ### I would like to do this under GSSoC'24
> ### Select program in which you are contributing
> GSSoC24
> 
> ### Code of Conduct
> * [x]  I follow CONTRIBUTING GUIDELINE of this project.

@Durgesh4993 Please Review it's allignment with project.

**Comment by sambitsingha** [comment]
@Durgesh4993 Kindly add the level ( for me , I think it is level 3) :))

**Comment by Durgesh4993** [comment]
Yup
