### ISSUE TITLE
[Bug]: Not able to close floating thing at right bottom

### ISSUE THREAD

**Issue by Ayush-may** [GameSphere-MultiPlayer/Community-Page#2]
### Give a brief about the bug ✍️

Im trying to close this but it is not closing , i think there is some issue in js 
![Screenshot from 2024-05-09 22-31-10](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/112775332/f53a413b-5c2c-44ff-a241-4cfec085be14)

### What is the expected behavior? 🤔

It should close when i press the close button but it is not closing .

### Provide step by step information reproduce the bug 📄

1. open the website 
2. Take your cursor to closing button of this floating thing
3. Try to click on that close button , it should close but it isnt closing

[Screencast from 09-05-24 10:28:24 PM IST.webm](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/112775332/af116b8a-c09d-495a-bef5-1fc89e37b164)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Ayush-may** [comment]
assign me this issue , i can fix this 
thanks !

**Comment by Aditya01229** [comment]
I've reviewed the JavaScript and identified an issue with event handling, which I've successfully resolved. Please assign this issue to me so that I can raise a pull request with the fix.

**Comment by Durgesh4993** [comment]
@Aditya01229 @Ayush-may , If you have any doubt you can directly as on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by SougataXdev** [comment]
@Durgesh4993 please assign this task to me

**Comment by Ayush-may** [comment]
@SougataXdev open a new issue and u will be assign in that

**Comment by SougataXdev** [comment]
I didn't get it , can you explain?

**Comment by SougataXdev** [comment]
I opened one

**Comment by SougataXdev** [comment]
@Ayush-may this is the additional one . main issue raised by me  is the upload button is not working.

**Comment by Nehakumari1208** [comment]
PLease assign this task to me...i will fix it

**Comment by Ayush-may** [comment]
@Nehakumari1208  PR is already created ! 
Find another issue and u will be assigned in that one
