### ISSUE TITLE
[New Feature]: fixing navbar

### ISSUE THREAD

**Issue by SougataXdev** [GameSphere-MultiPlayer/Community-Page#20]
### 🎮 feature Request

i can add the animation and design the navbar as requirement.

### Point down the features

adding the animation , fixing the navbar 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me

**Comment by Durgesh4993** [comment]
@Ramu-chiluveru @SougataXdev someone is already working on this issue. Please raise any other issue,  i'll assign you

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
