### ISSUE TITLE
[Bug]: upload button is not working  , discord closing (x) button is not working

### ISSUE THREAD

**Issue by SougataXdev** [GameSphere-MultiPlayer/Community-Page#21]
### Give a brief about the bug ✍️   

The upload button functionality is not working properly. When the button is pressed, it should open the file explorer menu for choosing files, but it currently does not respond. Additionally, there is an issue with the Discord popup not closing when the close button is clicked.

### What is the expected behavior? 🤔

Upload Button: When the upload button is pressed, it should trigger the file explorer menu to allow users to choose files for uploading.
Discord Popup: When the close button in the Discord popup is clicked, the popup should close,.
### Provide step by step information reproduce the bug 📄

- Navigate to the webpage containing the upload button.
- Click on the upload button.
- Observe that the file explorer menu does not appear.
- Navigate to the webpage containing the Discord popup.
- Click on the close button in the Discord popup.
- Observe that the popup does not close as expected.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by SougataXdev** [comment]
@Durgesh4993 assign this task to me i will fix it ASAP

**Comment by Pratyaksh0910** [comment]
Hey there! I'm Pratyaksh Agrawal, a full-stack MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC.
You can find me on LinkedIn : https://www.linkedin.com/in/pratyaksh-agrawal-2aa032220/
Looking forward to contributing to GSSOC 2024!

**Comment by SougataXdev** [comment]
@GameSphere-MultiPlayer please assign this issue to me

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me

**Comment by SougataXdev** [comment]
@Durgesh4993 @GameSphere-MultiPlayer issue fixed

**Comment by Ayush-may** [comment]
@SougataXdev this is duplicate issue of #2  where i already mentioned the close button issue

**Comment by Durgesh4993** [comment]
@SougataXdev I'll appreciate your learning spirit, but this PR is waste because this task is already assigned. Before sending OR you didn't discuss with me. I ma closing this issue.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
