### ISSUE TITLE
Join now text is not visible

### ISSUE THREAD

**Issue by Shreyaa173** [GameSphere-MultiPlayer/Community-Page#224]
### Give a brief about the bug ✍️

![Screenshot 2024-05-27 230351](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/144673309/c6ba2c9c-bf4a-422b-9f21-deecba0ac45d)
I want to change this. Please assign me

### What is the expected behavior? 🤔

Description

### Provide step by step information to reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Shreyaa173 Please raise any other issue, because someone is already working on it
