### ISSUE TITLE
Missing Dark/Light Mode on Webpage

### ISSUE THREAD

**Issue by Hemav009** [GameSphere-MultiPlayer/Community-Page#23]
### 🎮 feature Request

Hello @Durgesh4993 

I noticed that the webpage currently lacks support for dark and light modes. Adding dark and light modes would allow users to choose the theme that best suits their needs. I propose adding a **toggle button or menu option** that allows users to switch between dark and light modes seamlessly. Kindly assign me this issue.

Thank You!

### Point down the features

Display transition (dark/light)

### Select program in which you are contributing

GSSoc'24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by harshitsaxena214** [comment]
i would like to work on this issue please assign it to me

**Comment by KavyaBS123** [comment]
My name is Kavya B S and I'm a participant in the GIRL Script Summer of Code (GSSOC) program this year. I'm interested in contributing to the GameSphere project under GSSOC.
As this web page lacks the dark and light mode feature. It would be great if we add it soon.

I've been following GameSphere for a while now and I'm impressed with the idea.

To effectively contribute to the project, I'd be grateful if you could grant me contributor access to the repository on GitHub. This would allow me to submit pull requests with my code contributions.

I'm eager to learn and contribute to Gamesphere.
Please let me know if you require any further information from me. Thank you for your time and consideration.

**Comment by Durgesh4993** [comment]
@harshitsaxena214 @KavyaBS123 Please raise any other issue,  i'll assign you 

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
