### ISSUE TITLE
[Bug]:  The Navbar should be fixed at top so the user can use it anytime.

### ISSUE THREAD

**Issue by Utsavladia** [GameSphere-MultiPlayer/Community-Page#235]
### Give a brief about the bug ✍️

The Navbar should be fixed at top of the screen while scrolling so the user can use it anytime and improve the user experience.

### What is the expected behavior? 🤔

The Navbar should be fixed while scrolling on pages.

### Provide step by step information to reproduce the bug 📄

Scrolling on any page the navbar also scroll and goes up with page making it useless.
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/124615886/58a1b341-dddc-459d-9ca4-9744bf30b521)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Utsavladia** [comment]
I would love to contribute to this project and improve the user experience of using it. Please assign it to me😊

**Comment by Priyamjain1105** [comment]
Hi @Utsavladia ,

I'd like to work on issue #235. Can you please assign it to me?

Thanks

**Comment by Manaregr8** [comment]
Hi @Utsavladia ,

All issues related to the navbar and its responsiveness are being addressed at a level3 priority. I recommend that you continue to explore and bring up new issues with creativity aligned with technology, which I can then assign to you.

Thank you.
