### ISSUE TITLE
[Enhancement]: To make buttons in different sections appealing and interactive

### ISSUE THREAD

**Issue by Harsh-KumarJha** [GameSphere-MultiPlayer/Community-Page#237]
### 🎮 feature Request

The buttons on contribute and playgames pages are not interactive and visually aligned with the theme of the page. 

### Point down the features

I would like to make the enhancements in the viewing of the buttons by making it more visually appealing and adding the hover animations to make it interactive.

![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/121922047/709e22de-7da1-4868-8f33-f0e9fca9d9c1)
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/121922047/3a031620-0ff4-43a7-b493-b66d46e0633e)

Kindly assign this issue to me under GSSoC.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
This issue has already been addressed in #232. Please take a look at the project and identify some new issues.

Thank you
