### ISSUE TITLE
[Enhancement]:  To use latest social media logos on the page

### ISSUE THREAD

**Issue by Harsh-KumarJha** [GameSphere-MultiPlayer/Community-Page#238]
### 🎮 feature Request

The logos related to the social media handles are outdated.

### Point down the features

1. The logos for X (formerly twitter) needs to be updated
2. The Youtube logo is color switched i.e. it has red in place of white and white in place of the red

Logos being used:
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/121922047/157b2eb5-1568-4438-ba75-06ed00e286e0)

Original Youtube logo (present): 
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/121922047/1b9a9e06-482c-476a-8899-f2eabf2d53b8)

X(twitter) updated logo:
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/121922047/8c21aa45-ac8b-46a0-8379-86b69d125f43)

Kindly assign this issue to me under GSSoC. 
Thank You.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Priyamjain1105** [comment]
Hi @Harsh-KumarJha ,

I'd like to work on issue #42. Can you please assign it to me?

Thanks,

**Comment by Harsh-KumarJha** [comment]
Hi @Priyamjain1105 ,
I am not the project admin or owner; I am a contributor. I created the issue to work on it.

**Comment by Manaregr8** [comment]
HI @Harsh-KumarJha,
The Buttons that are present right now seems fine to me,
Please report new issues that works for responsiveness and enhancement of UI/UX of the website.

Thank You
