### ISSUE TITLE
Adding respective icons to the navbar

### ISSUE THREAD

**Issue by harshmishra19** [GameSphere-MultiPlayer/Community-Page#25]
### 🎮 feature Request

The current navbar lacks icons, which impacts its visual appeal and usability. Users might find it less engaging and intuitive to navigate through the website without visual cues provided by icons.

![Screenshot 2024-05-11 080754](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/115486960/a7ba373a-eca7-4c91-9b4d-b03966f3796a)

### Point down the features

- I propose adding respective icons to the navbar to enhance its visual appeal and improve user navigation experience. These icons will align with the theme of the website and provide users with clear visual cues for each navigation option.
- Adding icons is a more direct and effective solution to address the visual appeal and usability concerns of the navbar

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me

**Comment by Durgesh4993** [comment]
@harshmishra19 @Ramu-chiluveru Please raise any other issue because someone is already working on navigation bar enhancement
