### ISSUE TITLE
Sticky Navbar at Top

### ISSUE THREAD

**Issue by Aditi-P22** [GameSphere-MultiPlayer/Community-Page#27]
### 🎮 feature Request

This issue proposes the implementation of a sticky navigation bar at the top of the project's interface. A sticky navigation bar, once implemented, will enhance user experience by providing consistent access to essential navigation elements as users scroll through the content.

### Point down the features

feature points :
Persistent Navigation: The navbar remains visible at the top of the viewport even when the user scrolls down the page, ensuring easy access to navigation links and menu items at all times.

Improved Usability: Users can quickly navigate to different sections of the website or access important features without having to scroll back to the top of the page, thereby enhancing overall usability and user experience.

Consistency: By keeping the navigation bar fixed at the top, the layout remains consistent across different pages and screen sizes, providing a familiar and predictable interface for users.

Space Efficiency: A sticky navbar optimizes screen real estate by minimizing the need for a large, static navbar that occupies valuable space on the page. Instead, it collapses or shrinks as the user scrolls down, maximizing the available content area.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Aditi-P22** [comment]
Please assign this issue to me under GSSoC'24

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me.

**Comment by Durgesh4993** [comment]
@Aditi-P22 @Ramu-chiluveru Someone is already working on that, Please raise any other issue, i'll assign you

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
