### ISSUE TITLE
[New Feature]: Sticky top navbar

### ISSUE THREAD

**Issue by Ramu-chiluveru** [GameSphere-MultiPlayer/Community-Page#28]
### 🎮 feature Request

feature logic and basic description
feature points :
Persistent Navigation: The navbar remains visible at the top of the viewport even when the user scrolls down the page, ensuring easy access to navigation links and menu items at all times.

Improved Usability: Users can quickly navigate to different sections of the website or access important features without having to scroll back to the top of the page, thereby enhancing overall usability and user experience.

Consistency: By keeping the navigation bar fixed at the top, the layout remains consistent across different pages and screen sizes, providing a familiar and predictable interface for users.

Space Efficiency: A sticky navbar optimizes screen real estate by minimizing the need for a large, static navbar that occupies valuable space on the page. Instead, it collapses or shrinks as the user scrolls down, maximizing the available content area.

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Ramu-chiluveru** [comment]
As a GSsoc'24 contributer, I would like to work on this issue.So, I request you to  assign this to me.
@Durgesh4993

**Comment by Durgesh4993** [comment]
@Ramu-chiluveru Someone is already working on that issue, Please raise any other issue, then i'll assign you
