### ISSUE TITLE
[Bug]: Navbar and webpage  is not responsive 

### ISSUE THREAD

**Issue by GOURAVSINGH19** [GameSphere-MultiPlayer/Community-Page#32]
### Give a brief about the bug ✍️

Description
![Screenshot 2024-05-11 141636](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/120244528/45e01778-ddc5-4234-b742-f8b36cbb4c86)

As we can see the page is not responsive which is not for user experience.

![Screenshot 2024-05-11 141707](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/120244528/94a8155b-a4aa-41bb-a26e-75170cb32597)

 as you see the side cross btn is also not working .

I'd be happy to help you solve the issue! Could you please assign this issue to me.

### What is the expected behavior? 🤔

Description

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by kanikaa-3018** [comment]
the  navbar doesnt have any hover effects as well as the social media handles, please assign me this issue for GSSoc'24

**Comment by Durgesh4993** [comment]
@kanikaa-3018 @GOURAVSINGH19 Someone is already working on this issue, Please raise any other issue, i'll assign you
