### ISSUE TITLE
[style] Hover effect and github icon

### ISSUE THREAD

**Issue by chaanakyaaM** [GameSphere-MultiPlayer/Community-Page#35]
### Point down the features

Hey, your website is good, and it could be even better if the buttons on the nav bar have hover effect, and also it would be nice if the website has a GitHub icon which navigates to this repo, so that if anyone has any issues or new feature request, they could inform you.

## Features i would like to add:

- [X] Hover effect on the links of the nav bar.
- [X] GitHub icon on the left which navigates user to this repo.

### Select program in which you are contributing

GSSOC'24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

Just let me know by assigning me to this issue, if you are interested to view my PR.

**Comment by AmrutaJayanti** [comment]
Can you please assign this task to me

**Comment by Durgesh4993** [comment]
@chaanakyaaM @AmrutaJayanti Someone is already working on navigation bar, Please raise any other issue, i'll assign you

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
