### ISSUE TITLE
social media icons are not becoming larger when we hover on it

### ISSUE THREAD

**Issue by Nehakumari1208** [GameSphere-MultiPlayer/Community-Page#36]
social media icons are not becoming larger when we hover on it

**Comment by Nehakumari1208** [comment]
please assign this to me i will fix it

**Comment by KavyaBS123** [comment]
My name is Kavya B S and I'm a participant in the GIRL Script Summer of Code (GSSOC) program this year. I'm interested in contributing to the GameSphere project under GSSOC.

I've been following GameSphere for a while now and I'm impressed with the idea. 

To effectively contribute to the project, I'd be grateful if you could grant me contributor access to the repository on GitHub. This would allow me to submit pull requests with my code contributions.

I'm eager to learn and contribute to Gamesphere. 
Please let me know if you require any further information from me. Thank you for your time and consideration.

**Comment by Aleena-Memon** [comment]
please assign me this issue, so i can work on it under GSSOC24

**Comment by Durgesh4993** [comment]
@Aleena-Memon @KavyaBS123 Please raise any other issue, i'll assign you 

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
