### ISSUE TITLE
[New Feature]: Styling of navbar contents

### ISSUE THREAD

**Issue by vanisharma2003** [GameSphere-MultiPlayer/Community-Page#39]
### 🎮 feature Request

As this project is related to games. The navbar icons does not have proper styling according to the concept. I think that these icons styling should be more funky and should align more towards games theme. This will improve user experience.

### Point down the features

I will add a cool and funky styling to the content present in navbar. This will improve user experience and make design of the website more appealing.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by soham0005** [comment]
Hey, @vanisharma2003 can i work on this issue?, what I am thinking is creating pixelated social media icons using figma or canva and then add some animation using CSS and update it

**Comment by Durgesh4993** [comment]
@soham0005 @vanisharma2003 Someone is already working on navigation bar, Please raise any other issue,  i'll assign you 

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
