### ISSUE TITLE
[Bug]: Responsive issue

### ISSUE THREAD

**Issue by vignesh-0512** [GameSphere-MultiPlayer/Community-Page#41]
For mobile devices the website is not responsive.

For every devices like mobile,laptop,desktop it should be properly aligned automatically 

We can make the complete website as responsive using html,css and javascript.
![Screenshot_20240512-085616](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/115525353/f4cc2485-a8f3-4b3c-a09c-4c9409082b1b)

iam contributing under GSSOC'24

**Comment by Pratyaksh0910** [comment]
Hey there! I'm Pratyaksh Agrawal, a full-stack MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC.
You can find me on LinkedIn : https://www.linkedin.com/in/pratyaksh-agrawal-2aa032220/
Looking forward to contributing to GSSOC 2024!

@Durgesh4993

**Comment by manvichaudhary55** [comment]
I can make this page responsive . Please assign this issue to me under Gssoc'24.

**Comment by vverma022** [comment]
It's a simple issue I'd love to resolve the issue. Could I be assigned the issue

**Comment by vverma022** [comment]
> It's a simple issue I'd love to resolve the issue. Could I be assigned the issue

@Durgesh4993

**Comment by vignesh-0512** [comment]
@vverma022 iam not project assigned ask to project assigner I am also one of the Gssoc'24 contributor.

**Comment by Durgesh4993** [comment]
@Pratyaksh0910 @vverma022 @vignesh-0512 @manvichaudhary55 Please raise any other issue, because someone is already working on it..
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
