### ISSUE TITLE
[New Feature]: Moving the big discord item to simple social media bar icon at <760 px

### ISSUE THREAD

**Issue by PriyamvadaShah** [GameSphere-MultiPlayer/Community-Page#45]
### 🎮 feature Request

Feature Request
Feature logic and basic description

 Moving the big discord item to simple left hand-side social media bar icon at <760 px to increase visiblity of page.

### Point down the features

Feature points

Why should it be changed ?

The discord item is quite big and covers the whole page while scrolling.

![Screenshot 2024-05-12 132906](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/118747750/7a0f2032-6f24-4463-b1e3-c80e909038c4)

This works when we are working on a big screen but we have screens less than 760 px, it ends up blocking the whole page.
This can be simply resolved by moving it to the left hand side social media bar in smaller screens.

Also responsiveness of whole page can be improved. Beyond 760px, the upper part of the page is not properly functioning at all and even above 760px, the layout is not proper.

The procedure needs to be below the logo along with the upload button. 

Kindly assign me this issue so I can contribute to fix it. :)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@PriyamvadaShah Please raise any other issue, because someone is already working on it..
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by PriyamvadaShah** [comment]
Ok
