### ISSUE TITLE
[New Feature]: Discord item close button not working.

### ISSUE THREAD

**Issue by PriyamvadaShah** [GameSphere-MultiPlayer/Community-Page#46]
### 🎮 feature Request

feature logic and basic description

The discord item is not disappearing even when close button is clicked upon. 

### Point down the features

feature points

The discord item is not disappearing even when its close button is clicked upon. 

![Screenshot 2024-05-12 133601](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/118747750/ee435693-e6a1-404c-8d30-e5d1fd0accff)

This needs to be fixed to enhance user interaction.

Kindly assign me this issue for fixing. :)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@PriyamvadaShah Please raise any other issue, because someone is already working on it...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
