### ISSUE TITLE
[Bug]: Email Validation In Subscribe Option at bottom

### ISSUE THREAD

**Issue by say-het** [GameSphere-MultiPlayer/Community-Page#47]
### Give a brief about the bug ✍️

**Description**

 - Issue is that when I click subscribe to subscribe The Input box to enter email is not validated to input only emails.
 

### What is the expected behavior? 🤔

**Description**

 - This is because the field is not mandatory to enter only emails.

### Provide step by step information reproduce the bug 📄

**Description**

 - I have already fixed it, using only email to subscribe and it also says that you have subscribed after subscribing.
 
Please @Durgesh4993  assign this issue to me so that I can raise PR.

Little about me : I am experienced contributor as I have completed _Hacktoberfest-2020_ and _Hactoberfest-2023_ successfully.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by say-het** [comment]
Hey! @Durgesh4993 I have Successfully solved the issue and raised a PR.

Please check it.
