### ISSUE TITLE
Add customised scrollbar

### ISSUE THREAD

**Issue by Sneha123-zudo** [GameSphere-MultiPlayer/Community-Page#48]
### 🎮 feature Request

I want to add customised scrollbar to the website for enhancement of the website.

### Point down the features

The UI of the page will look nice.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Akshatakapare** [comment]
I would like to contribute to this issue. Please consider me for assigning this issue.

**Comment by Vaibhav-kesarwani** [comment]
i would like to work on this issue i have some experince making an website good UI desgins, so i will help you with that
