### ISSUE TITLE
[Bug]: Links of navbar are not working

### ISSUE THREAD

**Issue by Ridhima10** [GameSphere-MultiPlayer/Community-Page#49]
### Give a brief about the bug ✍️

The links of navbar are not redirecting to the desired page

### What is the expected behavior? 🤔

It should be  clickable so that we can surf through the website to make it user friendly

### Provide step by step information reproduce the bug 📄

I will add the path of all the pages so that it will be easy for user to navigate

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Coder-Kartikey** [comment]
Navbar links are not working i will make them working and i will also create about us page so that it will brief about the site . 
@Durgesh4993  Assign this issue to me under GSSoC'24. 

I will love to contribute on this project. I will give my full efforts to make it better and better.
Thank You!

**Comment by Durgesh4993** [comment]
@Ridhima10 @Coder-Kartikey we don't have pages for continue, if you are intrested you can create page  i'll assign you
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Ridhima10** [comment]
@Durgesh4993  I will make about page first and then connect it with the navbar
After that i will make more pages

since you have assigned me to make about page ,kindly assign me this too so that i can connect it with navbar

**Comment by Coder-Kartikey** [comment]
No problem, @Durgesh4993 i will make pages for it and then connect to the site . If you assign me this i will start working immediately.

**Comment by Vaibhav-kesarwani** [comment]
@Ridhima10 assign this issue to me and i will help you with that!!
