### ISSUE TITLE
[New Feature]:  Create About page

### ISSUE THREAD

**Issue by Ridhima10** [GameSphere-MultiPlayer/Community-Page#50]
### 🎮 feature Request

i want to add a about page in your website

### Point down the features

I would like to create the about page of the website so that it will be easy for users to know the details / information of the website

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
