### ISSUE TITLE
[Bug]: social media links are not working on clicking

### ISSUE THREAD

**Issue by Ridhima10** [GameSphere-MultiPlayer/Community-Page#51]
### Give a brief about the bug ✍️

When we click on social media icons they are not redirecting to that particular social media platform

### What is the expected behavior? 🤔

The icons should be clickable and redirected to desired page

### Provide step by step information reproduce the bug 📄

I will add the paths of the social media website so it will enhance the UX and function properly

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Ridhima10 Please raise any other issue, because someone is already working on it...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
