### ISSUE TITLE
[New Feature]: Change icons of progress 

### ISSUE THREAD

**Issue by Ridhima10** [GameSphere-MultiPlayer/Community-Page#52]
### 🎮 feature Request

I would like to change the icon of progress section to a more appealing icon to enhance the UI of the webpage.
![Screenshot 2024-05-12 195321](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/85826117/52549244-4fdf-4005-a0af-3c4278a995f5)

### Point down the features

I am planning to give it a gradient which matches your theme
![Screenshot 2024-05-12 195542](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/85826117/1b696928-7a39-48c1-8ab3-290c2e5aed62)

It will make the UI more attractive

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
