### ISSUE TITLE
Not Responsive 

### ISSUE THREAD

**Issue by NitinChakrawarti** [GameSphere-MultiPlayer/Community-Page#54]
### Give a brief about the bug ✍️

website is not responsive to different  devices 
![WhatsApp Image 2024-05-12 at 21 30 15_36145f36](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/149225785/80b807a6-addd-47b3-bc4a-6a09f73e3b49)
![Screenshot 2024-05-12 212715](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/149225785/decf5325-4763-41e6-8f65-ca1c7e85fe0d)
![Screenshot 2024-05-12 212738](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/149225785/d06f7f5a-d51a-4f97-b0ab-c73f618d1c79)

### What is the expected behavior? 🤔

All elements has to be in screen and adapt as per size of screen

### Provide step by step information reproduce the bug 📄

I can make it responsive using media queries in CSS for different breakpoints.  which make it responsive to different devices.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@NitinChakrawarti Please raise any other issue, because someone is already working on it...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
