### ISSUE TITLE
footer section needs  some improvement

### ISSUE THREAD

**Issue by reshamsai150** [GameSphere-MultiPlayer/Community-Page#55]
### 🎮 Feature Request

making some hovering effects adding some responsiveness, and making the footer section more attractive

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@reshamsai150 Could you please explain more what you want to do, if possible you can also add screenshot...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by reshamsai150** [comment]
![IMG-20240513-WA0000(1)](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/164533685/63de52f1-7410-40a9-8587-bb816b634abb)
I want to add hovering effect to headings in footer  as well as list elements and also add  hovering effect to  email button and changing color on hovering the  email button

**Comment by GeeekySouro003** [comment]
please assgin this task to meee as this could be the start of contributing to open sourcee

**Comment by Mukesh751** [comment]
> ![IMG-20240513-WA0000(1)](https://private-user-images.githubusercontent.com/164533685/329909106-63de52f1-7410-40a9-8587-bb816b634abb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTg2OTEsIm5iZiI6MTcxNTcxODM5MSwicGF0aCI6Ii8xNjQ1MzM2ODUvMzI5OTA5MTA2LTYzZGU1MmYxLTc0MTAtNDBhOS04NTg3LWJiODE2YjYzNGFiYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQyMDI2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjc2MDVjNzI2NzRiYzI5YjRlMTRjOGMxNmIwZjk5ZWYwNDM3ZTZkMzZjZTdhNGE3Y2M0NjU3NDg0NTQyMmYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.58axQbWSkccnTA5ufl1xzNbkpV5YbNNX6RAxEOAIOJg) @Durgesh4993 I want to add a hovering effect to headings in the footer as well as list elements and also add a hovering effect to the email button and change color on hovering the email button

Hovering effect is already there on the list of items and email i guess
