### ISSUE TITLE
Link Navbar Tabs and Enhance Content

### ISSUE THREAD

**Issue by Shreesanyog** [GameSphere-MultiPlayer/Community-Page#59]
## Overview
Some tabs in the navigation bar currently do not have content, which results in the absence of corresponding links. This issue aims to address that by providing content for these tabs and establishing links to their respective pages.

## Goals
- To create and add relevant content for each unlinked tab in the navbar.
- To link these tabs to new or existing pages that reflect the added content.

## Action Plan
1. Identify all unlinked tabs in the navbar.
2. Develop content that is informative and relevant for each tab.
3. Create new pages or sections as needed to host this content.
4. Implement navigation links from each tab to its new content page or section.

## GSSoC Contribution
I am proposing these changes as part of my contributions to the GirlScript Summer of Code (GSSoC). I am ready to draft the content, design the pages, and execute the necessary code changes to enhance the project's navigation experience.

Please let me know if you're open to these enhancements, and I'll get started on the work right away. And please add labels to it.

### Point down the features

Adding content and navigation links

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Shreesanyog Could you please explain more what you want to do, if possible you can also add screenshot.
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Shreesanyog** [comment]
Hello @Durgesh4993 ,

Thank you for the opportunity to clarify. I have reviewed the website and here are my observations and proposed contributions:

1. **About Us Section**: Currently, this section does not contain detailed information about the project. I plan to write a comprehensive overview that introduces  the project's mission.

2. **Products Section**: This section appears empty at the moment. I propose to add descriptions of the available products. For example, I can detail the features of your games like 'Dot-Box', 'Car-Racing', etc., and provide links to these games so users can easily find and enjoy them.

3. **Contributions Section**: Similar to the 'Products' section, there is a lack of content here. I will add some content here as well.

I believe these enhancements will not only improve the navigation but also enrich the content, making the website more informative and engaging for visitors.

I am attaching a screenshot of the current webpage to illustrate the sections mentioned above.
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/166977453/f4507362-40c0-4289-b12d-65496d16f818)


I look forward to your feedback and am excited to start working on these improvements.
