### ISSUE TITLE
[New Feature]: Adding website logo on the header

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [GameSphere-MultiPlayer/Community-Page#60]
### 🎮 feature Request

![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/125277258/4d2133eb-d6ff-4c82-b67b-fd071414df1c)
for adding the logo here.

### Point down the features

feature points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@RamakrushnaBiswal Please raise any other issue, because someone is already working on it
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
