### ISSUE TITLE
[New Feature]: Hiding the component when user clicks on cut (x) button.

### ISSUE THREAD

**Issue by unstoppableayush** [GameSphere-MultiPlayer/Community-Page#61]
### 🎮 feature Request

feature logic and basic description
![issue cut](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/75977554/2b10b815-ec92-4568-9198-6d193bf93149)

I want to implement this feature.

### Point down the features

When the user clicks on the cut button then that component will be hidden.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@unstoppableayush Please raise any other issue, because someone is already working on it
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
