### ISSUE TITLE
[New Feature]: No logo on the title and some buttons are not working

### ISSUE THREAD

**Issue by Amitesh-Mishra-AM** [GameSphere-MultiPlayer/Community-Page#63]
### 🎮 feature Request

![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/86422382/27853ba7-3d8c-421a-b63b-88e88170bdc3)
###  I'll implement a feature where the 'Welcome to our Discord server' message closes when users click the cross button. After closing, it'll be replaced by the Discord logo. Clicking on the logo will reopen the message.
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/86422382/78bc28eb-d144-405f-bd86-173296cb7e94)

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Amitesh-Mishra-AM Please raise any other issue, because someone is already working on it
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
