### ISSUE TITLE
[Bug]:  cancel button is no working

### ISSUE THREAD

**Issue by NitinChakrawarti** [GameSphere-MultiPlayer/Community-Page#65]
### Give a brief about the bug ✍️

Description

in footer section join discord is visible always

### What is the expected behavior? 🤔

Description:- it should disappear  on click  cancel button.

![Screenshot 2024-05-13 190045](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/149225785/4ded6ea0-b1f2-4e51-b667-5872d99583f3)

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Ankur-Rai-19** [comment]
## Here are the changes, after clicking on the 'close' button, it gets closed.

### Kindly assign the task to me, so that I can commit and push the changes. 



https://github.com/GameSphere-MultiPlayer/Community-Page/assets/125396300/65d060b1-5490-47c1-9ebf-ec37a576a89b

**Comment by Durgesh4993** [comment]
@Ankur-Rai-19 @NitinChakrawarti Please raise any other issue, because someone is already working on it....
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
