### ISSUE TITLE
[Bug]: Responsive Issue

### ISSUE THREAD

**Issue by sivaprasath2004** [GameSphere-MultiPlayer/Community-Page#66]
### Give a brief about the bug ✍️

- if the `Tab` and `mobile` mode has not proper responsive the text `overflow ` of the container..
- If i will ready work on this project please assign me i will be ready for this..

### What is the expected behavior? 🤔

- `mobile` and `Tab` was proper responsive will be user expected but it not responsive...

### Provide step by step information reproduce the bug 📄

![Screenshot from 2024-05-13 21-49-19](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/121082414/4bbfd65f-47eb-41b0-b20c-a8cc71f45a43)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@sivaprasath2004 Please raise any other issue, because someone is already working on it...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
