### ISSUE TITLE
[New Feature]:  Improve the onclick of the Join discord server

### ISSUE THREAD

**Issue by MetiUmashri** [GameSphere-MultiPlayer/Community-Page#71]
### 🎮 feature Request

Basically at the end of the website the Join discord server is not vanishing upon clicking the cancel symbol, so i would work on that. Apart from that automatic scroll to the beginning of the web page upon reaching the end of the website.

### Point down the features

Basically at the end of the website the Join discord server is not vanishing upon clicking the cancel symbol, so i would work on that. Apart from that automatic scroll to the beginning of the web page upon reaching the end of the website. By improvising these this can make the website more interactive.

KINDLY ASSIGN THIS ISSUE TO ME I WOULD DEFINITELY WORK ON IT

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@MetiUmashri Please raise any other issue, because someone is already working on it..
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
