### ISSUE TITLE
[New Feature]: Improvement of social link to share button view . Assign under GSSOC'24

### ISSUE THREAD

**Issue by Anjaliavv51** [GameSphere-MultiPlayer/Community-Page#76]
### 🎮 feature Request

Footer Share option's below email input:
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/154777864/69289636-7ec1-425c-a7b6-44fb6b5b0470)

Feature i want to improve for share option:
It reduces space and also looks attractive due it's transform.

### Point down the features

Feature i want to improve for share option:

https://github.com/GameSphere-MultiPlayer/Community-Page/assets/154777864/abbf18c9-2a23-4bcf-a50f-83788511dacc

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Anjaliavv51** [comment]
Okay

**Comment by Anjaliavv51** [comment]
Check the PR #86 
And merge the files.
And also add label's for PR #86

**Comment by Anjaliavv51** [comment]
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/154777864/48ccd0bd-349b-4362-926c-44ccdd8b63d8)

Check the PR https://github.com/GameSphere-MultiPlayer/Community-Page/pull/86
And merge the files.
And also add label's for PR https://github.com/GameSphere-MultiPlayer/Community-Page/pull/86
GSSOC enhancement Level2 labels.

**Comment by Anjaliavv51** [comment]
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/154777864/5e3d33f7-7d83-4016-9ed3-5ab31d59deaa)
