### ISSUE TITLE
[New Feature]: Routing of various tabs in the navbar

### ISSUE THREAD

**Issue by Roshr2211** [GameSphere-MultiPlayer/Community-Page#78]
### 🎮 feature Request

feature logic and basic description
# Issue 
- there is no routing or linking to other tabs . The about page is created but cannot be used unless linking isnt given. 

https://github.com/GameSphere-MultiPlayer/Community-Page/assets/136987759/335dcc40-74cb-4158-9b4f-5e130af7582d

### Point down the features

feature points
# Solution
providing the link to various tabs to access all the tabs [ for now since about us page is created it has been created, the routing has been done ] 

https://github.com/GameSphere-MultiPlayer/Community-Page/assets/136987759/f4d70cf3-fb1e-4f21-a630-d11fc636863b

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by mtg718** [comment]
Please assign me this issue under GSSoc'24.
