### ISSUE TITLE
[Bug]: Change color of search icon on cicking

### ISSUE THREAD

**Issue by Ridhima10** [GameSphere-MultiPlayer/Community-Page#83]
### Give a brief about the bug ✍️

The icon of search is initially white but hen we click on it is black which is not visible that much. I would like to fix it
![Screenshot 2024-05-14 182042](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/85826117/06919342-b852-4c50-8943-577020669401)
![Screenshot 2024-05-14 182111](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/85826117/e4e43e4c-79fa-4963-9cdb-403a190e309b)

### What is the expected behavior? 🤔

the color of the icon should be white

### Provide step by step information reproduce the bug 📄

 I will find the class and then change the color by giving it priority so that in any case it does not overrides any other property

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Ridhima10 and also reduced the margin of navigation

**Comment by mtg718** [comment]
Please assign me this issue under GSSoc'24.

**Comment by Ridhima10** [comment]
@Durgesh4993  Kindly review this

**Comment by Manaregr8** [comment]
> @Durgesh4993 Kindly review this

Nicely done, find more issues and get them.
