### ISSUE TITLE
[Bug]: 1. Favicon absent , 2.About ,Home, Contribute page are not hyperlinked

### ISSUE THREAD

**Issue by curecode11** [GameSphere-MultiPlayer/Community-Page#87]
### Give a brief about the bug ✍️

Header section links are going no where also the website is missing a favicon which always create a good impression about the site.
I can make the about and contribute page also will add the favicon .

### What is the expected behavior? 🤔

Interlinking should be there between header section links.

### Provide step by step information reproduce the bug 📄

just click on the links you will go nowhere 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by curecode11** [comment]
@Durgesh4993  sir i am willing to do above task , kindly assign this issue to me, I will be happy to work

**Comment by Manaregr8** [comment]
> ### Give a brief about the bug ✍️
> Header section links are going no where also the website is missing a favicon which always create a good impression about the site. I can make the about and contribute page also will add the favicon .
> 
> ### What is the expected behavior? 🤔
> Interlinking should be there between header section links.
> 
> ### Provide step by step information reproduce the bug 📄
> just click on the links you will go nowhere
> 
> ### Select program in which you are contributing
> GSSoC24
> 
> ### Code of Conduct
> * [x]  I follow CONTRIBUTING GUIDELINE of this project.

Adding a favicon is a Level One issue. Other links in the header will be added after a review. If required, I will assign them to you in the future.
